/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huawe
 */
public class PersonelFrame extends javax.swing.JFrame {

    /**
     * Creates new form PersonelFrame
     */
    public PersonelFrame() {
        initComponents();
        setLocation(500, 250);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        güncellemebutonu = new javax.swing.JButton();
        listele = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gün = new javax.swing.JComboBox<>();
        ID = new javax.swing.JTextField();
        ad = new javax.swing.JTextField();
        Soyad = new javax.swing.JTextField();
        maaş = new javax.swing.JTextField();
        ySehir = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        ekle = new javax.swing.JButton();
        ay = new javax.swing.JComboBox<>();
        sil = new javax.swing.JButton();
        yıl = new javax.swing.JTextField();
        SıralamaButon = new javax.swing.JButton();
        scombo = new javax.swing.JComboBox<>();
        Aranan = new javax.swing.JTextField();
        AramaButon = new javax.swing.JButton();
        acombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        IDsıralamaButon = new javax.swing.JButton();
        İSimSıralaButon = new javax.swing.JButton();
        SoyİsimSırala = new javax.swing.JButton();
        DTSıralamaButonu = new javax.swing.JButton();
        yŞehirSıralamaButonu = new javax.swing.JButton();
        MaşşSıralamaButonu = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 102));
        setFocusCycleRoot(false);
        setLocation(new java.awt.Point(500, 250));

        güncellemebutonu.setBackground(new java.awt.Color(204, 255, 255));
        güncellemebutonu.setText("Güncelle");
        güncellemebutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncellemebutonuActionPerformed(evt);
            }
        });

        listele.setBackground(new java.awt.Color(204, 255, 255));
        listele.setText("Listele");
        listele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeleActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("Ad");

        jLabel4.setText("Soyad");

        jLabel5.setText("Maaş");

        jLabel6.setText("Yaşadığı Şehir");

        jLabel7.setText("Doğum Günü");

        gün.setBackground(new java.awt.Color(186, 186, 250));
        gün.setEditable(true);
        gün.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        ID.setBackground(new java.awt.Color(186, 186, 250));
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        ad.setBackground(new java.awt.Color(186, 186, 250));
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });

        Soyad.setBackground(new java.awt.Color(186, 186, 250));

        maaş.setBackground(new java.awt.Color(186, 186, 250));

        ySehir.setBackground(new java.awt.Color(186, 186, 250));
        ySehir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ySehirActionPerformed(evt);
            }
        });

        tablo.setBackground(new java.awt.Color(204, 255, 255));
        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "İsim", "Soyisim", "Doğum Tarihi", "Maaş", "Yaşadığı Şehir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablo.setColumnSelectionAllowed(true);
        tablo.setFocusable(false);
        tablo.setGridColor(new java.awt.Color(0, 255, 102));
        tablo.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabloMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabloMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablo);
        tablo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablo.getAccessibleContext().setAccessibleName(getName());
        tablo.getAccessibleContext().setAccessibleDescription(getName());

        ekle.setBackground(new java.awt.Color(204, 255, 255));
        ekle.setText("Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        ay.setBackground(new java.awt.Color(186, 186, 250));
        ay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        sil.setBackground(new java.awt.Color(204, 255, 255));
        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        yıl.setBackground(new java.awt.Color(186, 186, 250));
        yıl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yılActionPerformed(evt);
            }
        });

        SıralamaButon.setText("Sıralama");
        SıralamaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SıralamaButonActionPerformed(evt);
            }
        });

        scombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S. çeşidi", "ıd", "ad", "soyad", "maaşBüyük", "maaşKüçük", "y.Şehir", "yaşBüyük", "yaşKüçük" }));

        Aranan.setBackground(new java.awt.Color(186, 186, 250));
        Aranan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArananActionPerformed(evt);
            }
        });

        AramaButon.setText("Arama");
        AramaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AramaButonActionPerformed(evt);
            }
        });

        acombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A. şekli", "Id", "Ad", "Soyad" }));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Textleri temizle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        IDsıralamaButon.setBackground(new java.awt.Color(204, 255, 255));
        IDsıralamaButon.setText("ID Sırala");
        IDsıralamaButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDsıralamaButonMouseClicked(evt);
            }
        });
        IDsıralamaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDsıralamaButonActionPerformed(evt);
            }
        });

        İSimSıralaButon.setBackground(new java.awt.Color(204, 255, 255));
        İSimSıralaButon.setText("İsim Sırala");
        İSimSıralaButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                İSimSıralaButonMouseClicked(evt);
            }
        });

        SoyİsimSırala.setBackground(new java.awt.Color(204, 255, 255));
        SoyİsimSırala.setText("Soyisim Sıralama");
        SoyİsimSırala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SoyİsimSıralaMouseClicked(evt);
            }
        });

        DTSıralamaButonu.setBackground(new java.awt.Color(204, 255, 255));
        DTSıralamaButonu.setText("D.Tarihi Sıralama");
        DTSıralamaButonu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DTSıralamaButonuMouseClicked(evt);
            }
        });

        yŞehirSıralamaButonu.setBackground(new java.awt.Color(204, 255, 255));
        yŞehirSıralamaButonu.setText("Şehir Sıralama");
        yŞehirSıralamaButonu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yŞehirSıralamaButonuMouseClicked(evt);
            }
        });

        MaşşSıralamaButonu.setBackground(new java.awt.Color(204, 255, 255));
        MaşşSıralamaButonu.setText("Maaş Sıralama");
        MaşşSıralamaButonu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaşşSıralamaButonuMouseClicked(evt);
            }
        });

        jMenu3.setText("Menü");
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maaş, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ySehir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(AramaButon)
                            .addComponent(SıralamaButon))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gün, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yıl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Aranan, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(acombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(Soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sil, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(güncellemebutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listele, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDsıralamaButon, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(İSimSıralaButon, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SoyİsimSırala, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DTSıralamaButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MaşşSıralamaButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yŞehirSıralamaButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7)
                                .addComponent(gün, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yıl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(SıralamaButon)
                            .addComponent(scombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maaş, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ySehir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AramaButon)
                                    .addComponent(Aranan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ekle)
                                .addGap(35, 35, 35))
                            .addComponent(sil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(güncellemebutonu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listele)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDsıralamaButon)
                        .addComponent(İSimSıralaButon)
                        .addComponent(SoyİsimSırala)
                        .addComponent(DTSıralamaButonu))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MaşşSıralamaButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yŞehirSıralamaButonu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void güncellemebutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncellemebutonuActionPerformed
        PersonelFrame frame = new PersonelFrame();
        MsSqlConnection msql = new MsSqlConnection();
        Statement stmt = null;
        int sayaç = 0;
        if (!ad.getText().equals("") || !ySehir.getText().equals("") || !yıl.getText().equals("") || !maaş.getText().equals("") || !Soyad.getText().equals("")) {
            try {
                stmt = msql.stmtver();
            } catch (SQLException ex) {
                Logger.getLogger(PersonelFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            String tmp = ID.getText();
            int id = Integer.parseInt(tmp);

            if (!ad.getText().equals("")) {
                String isim = ad.getText();
                String geçici = "Update Personel Set adi='" + isim + "' where id= " + id;
                try {
                    stmt.execute(geçici);
                } catch (SQLException ex) {
                    Logger.getLogger(PersonelFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Güncellendi");

                sayaç++;
            }
            if (!Soyad.getText().equals("")) {
                String soyad = Soyad.getText();
                String geçici = "Update Personel Set soyadi='" + soyad + "' where id= " + id;
                try {
                    stmt.execute(geçici);
                } catch (SQLException ex) {
                    Logger.getLogger(PersonelFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Güncellendi");

                sayaç++;
            }
            if (!maaş.getText().equals("")) {
                String ücret = maaş.getText();
                int i = Integer.parseInt(ücret);
                String geçici = "Update Personel Set maaş='" + i + "' where id= " + id;
                try {
                    stmt.execute(geçici);
                } catch (SQLException ex) {
                    Logger.getLogger(PersonelFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Güncellendi");

                sayaç++;
            }
            if (!yıl.getText().equals("")) {
                String dogTah = "";

                String yılı = yıl.getText();

                dogTah += yılı + "-";
                String ayı = (String) ay.getSelectedItem().toString();
                dogTah += ayı + "-";
                String günü = (String) gün.getSelectedItem().toString();
                dogTah += günü;
                String geçici = "Update Personel Set dogTah='" + dogTah + "' where id= " + id;
                try {
                    stmt.execute(geçici);
                } catch (SQLException ex) {
                    Logger.getLogger(PersonelFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Güncellendi");
                sayaç++;
            }
            if (!ySehir.getText().equals("")) {
                String sehir = ySehir.getText();
                String geçici = "Update Personel Set ySehir='" + sehir + "' where id= " + id;
                try {
                    stmt.execute(geçici);
                } catch (SQLException ex) {
                    Logger.getLogger(PersonelFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Güncellendi");
            } else {
                JOptionPane.showMessageDialog(frame, "Güncellemek için güncellemek istediğiniz alanın ve id nin dolu olduğundan emin olunuz ");
            }
            if (sayaç > 0) {
                JOptionPane.showMessageDialog(frame, "Kişi güncellendi ");
            } else {
                JOptionPane.showMessageDialog(frame, "Güncellemek için güncellemek istediğiniz alanın ve id nin dolu olduğundan emin olunuz ");
            }
            sayaç = 0;
            ID.setText("");

            ad.setText("");
            Soyad.setText("");
            maaş.setText("");
            ySehir.setText("");
            Aranan.setText("");
            yıl.setText("");
            gün.setSelectedIndex(0);
            ay.setSelectedIndex(0);
            scombo.setSelectedIndex(0);
            acombo.setSelectedIndex(0);
            PersonelFrame f = new PersonelFrame();
        } else {
            PersonelFrame f = new PersonelFrame();
            JOptionPane.showMessageDialog(frame, "Lütfen Kişi Bilgilerini güncellemek için id ve güncellenecek alanın dolu olduğundan emin olunuz");
        }
    }//GEN-LAST:event_güncellemebutonuActionPerformed

    private void listeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeleActionPerformed

        MsSqlConnection msql = new MsSqlConnection();

        String sql = "select * from Personel ";

        tablo.setModel(msql.eListele(sql));


    }//GEN-LAST:event_listeleActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed

    }//GEN-LAST:event_IDActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adActionPerformed

    private void ySehirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ySehirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ySehirActionPerformed

    private void tabloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloMousePressed
        try {
            int satır = tablo.getSelectedRow();//Hangi satır olduğunu alıyor.
            MsSqlConnection msql = new MsSqlConnection();
            int b = 0;
            Statement stmt = msql.stmtver();
            String sql = "select * from Personel ";
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                if (b == satır) {

                    String id = rs.getString("id");
                    String adi = rs.getString("adi");
                    String soyadi = rs.getString("soyadi");
                    String maaşi = rs.getString("maaş");
                    String şehiri = rs.getString("ySehir");
                    ID.setText(id);
                    ad.setText(adi);
                    Soyad.setText(soyadi);
                    maaş.setText(maaşi);
                    ySehir.setText(şehiri);
                    Aranan.setText("");
                    String dt = rs.getString("dogTah");

                    String yılı = dt.substring(0, 4);
                    String ayı = dt.substring(5, 7);
                    String günü = dt.substring(9, 10);

                    yıl.setText(yılı);
                    int i = Integer.parseInt(ayı);
                    int j = Integer.parseInt(günü);
                    gün.setSelectedIndex(j - 1);
                    ay.setSelectedIndex(i - 1);

                    b++;
                }
                b++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(PersonelFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabloMousePressed

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        MsSqlConnection msql = new MsSqlConnection();
        String dogTah = "";

        String yılı = yıl.getText();

        dogTah += yılı + "-";
        String ayı = (String) ay.getSelectedItem().toString();
        dogTah += ayı + "-";
        String günü = (String) gün.getSelectedItem().toString();
        dogTah += günü;
        Statement stmt = null;
        try {
            stmt = msql.stmtver();
        } catch (SQLException ex) {

        }
        String isim = ad.getText();
        String soyad = Soyad.getText();
        String ücret = maaş.getText();
        int i = Integer.parseInt(ücret);
        String sehir = ySehir.getText();
        //              System.out.println(günü);

        try {
            msql.add(isim, soyad, dogTah, i, sehir, stmt);
        } catch (SQLException ex) {
            Logger.getLogger(PersonelFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        ID.setText("");
        ad.setText("");
        Soyad.setText("");
        maaş.setText("");
        ySehir.setText("");
        Aranan.setText("");
        yıl.setText("");
        gün.setSelectedIndex(0);
        ay.setSelectedIndex(0);
        scombo.setSelectedIndex(0);
        acombo.setSelectedIndex(0);
        PersonelFrame frame = new PersonelFrame();
        JOptionPane.showMessageDialog(frame, "Kişi eklendi");
    }//GEN-LAST:event_ekleActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        PersonelFrame frame = new PersonelFrame();
        MsSqlConnection msql = new MsSqlConnection();

        String geçici = ID.getText();
        if (ID.getText().equals("")) {
            JOptionPane.showMessageDialog(frame, "Kişi silmek için lütfen id giriniz");
        } else {
            int id = Integer.parseInt(geçici);
            final JLabel label = new JLabel();
            int result = JOptionPane.showConfirmDialog(frame, "Silmek İstediğinize emin misiniz?", "Kayıt silme",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                try {
                    msql.delete(id, msql.stmtver());
                    JOptionPane.showMessageDialog(frame, "Kişi silindi");
                } catch (SQLException ex) {
                    Logger.getLogger(PersonelFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                ID.setText("");
                ad.setText("");
                Soyad.setText("");
                maaş.setText("");
                ySehir.setText("");
                Aranan.setText("");
                yıl.setText("");
                gün.setSelectedIndex(0);
                ay.setSelectedIndex(0);
                scombo.setSelectedIndex(0);
                acombo.setSelectedIndex(0);

            } else if (result == JOptionPane.NO_OPTION) {
                label.setText("Hayırı Seçtin");
            } else {
                label.setText("Seçim yapılmadı");
            }
        }

    }//GEN-LAST:event_silActionPerformed

    private void yılActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yılActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yılActionPerformed

    private void ArananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArananActionPerformed

    private void SıralamaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SıralamaButonActionPerformed
        PersonelFrame frame = new PersonelFrame();
        if (scombo.getSelectedItem().toString().equals("S. çeşidi")) {

            JOptionPane.showMessageDialog(frame, "Lütfen Sıralama Yöntemini Seçiniz");

        } else {
            if (scombo.getSelectedItem().toString().equals("ıd")) {

                MsSqlConnection msql = new MsSqlConnection();

                String sql = "select * from Personel order by id ";

                tablo.setModel(msql.eListele(sql));

            } else if (scombo.getSelectedItem().toString().equals("ad")) {
                MsSqlConnection msql = new MsSqlConnection();

                String sql = "select * from Personel order by adi ";

                tablo.setModel(msql.eListele(sql));

            } else if (scombo.getSelectedItem().toString().equals("soyad")) {
                MsSqlConnection msql = new MsSqlConnection();

                String sql = "select * from Personel order by soyadi ";

                tablo.setModel(msql.eListele(sql));
            } else if (scombo.getSelectedItem().toString().equals("maaşBüyük")) {
                MsSqlConnection msql = new MsSqlConnection();

                String sql = "select * from Personel order by maaş desc ";

                tablo.setModel(msql.eListele(sql));
            } else if (scombo.getSelectedItem().toString().equals("maaşKüçük")) {
                MsSqlConnection msql = new MsSqlConnection();

                String sql = "select * from Personel order by maaş ";

                tablo.setModel(msql.eListele(sql));
            } else if (scombo.getSelectedItem().toString().equals("y.Şehir")) {
                MsSqlConnection msql = new MsSqlConnection();

                String sql = "select * from Personel order by ySehir ";

                tablo.setModel(msql.eListele(sql));
            } else if (scombo.getSelectedItem().toString().equals("yaşBüyük")) {
                MsSqlConnection msql = new MsSqlConnection();

                String sql = "select * from Personel order by dogTah ";

                tablo.setModel(msql.eListele(sql));
            } else if (scombo.getSelectedItem().toString().equals("yaşKüçük")) {
                MsSqlConnection msql = new MsSqlConnection();

                String sql = "select * from Personel order by dogTah desc ";

                tablo.setModel(msql.eListele(sql));
            }
        }
    }//GEN-LAST:event_SıralamaButonActionPerformed

    private void AramaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AramaButonActionPerformed

        PersonelFrame frame = new PersonelFrame();
        MsSqlConnection msql = new MsSqlConnection();
        String geçici = Aranan.getText();

        if (acombo.getSelectedItem().toString().equals("A. şekli")) {
            JOptionPane.showMessageDialog(frame, "Lütfen Arama Yöntemini Seçiniz");
        } else {

            switch (acombo.getSelectedItem().toString()) {
                case "Ad":

                    String sql = "select * from Personel Where adi='";
                    System.out.println(geçici);
                    sql += geçici + "'";
                    tablo.setModel(msql.eListele(sql));
                    break;
                case "Soyad":

                    sql = "select * from Personel Where soyadi='";
                    sql += geçici + "'";
                    tablo.setModel(msql.eListele(sql));
                    break;
                case "Id":

                    sql = "select * from Personel Where id=";
                    sql += geçici;
                    tablo.setModel(msql.eListele(sql));
            }
        }
    }//GEN-LAST:event_AramaButonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ID.setText("");
        ad.setText("");
        Soyad.setText("");
        maaş.setText("");
        ySehir.setText("");
        Aranan.setText("");
        yıl.setText("");
        gün.setSelectedIndex(0);
        ay.setSelectedIndex(0);
        scombo.setSelectedIndex(0);
        acombo.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloMouseClicked

    }//GEN-LAST:event_tabloMouseClicked

    private void IDsıralamaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDsıralamaButonActionPerformed


    }//GEN-LAST:event_IDsıralamaButonActionPerformed

    private void IDsıralamaButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDsıralamaButonMouseClicked

        PersonelFrame frame = new PersonelFrame();

        MsSqlConnection msql = new MsSqlConnection();

        if (evt.getClickCount() == 1) {

            String sql = "select * from Personel order by id";

            tablo.setModel(msql.eListele(sql));
        }
        if (evt.getClickCount() == 2) {

            String sql = "select * from Personel order by id desc";

            tablo.setModel(msql.eListele(sql));

        }


    }//GEN-LAST:event_IDsıralamaButonMouseClicked

    private void İSimSıralaButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_İSimSıralaButonMouseClicked

        PersonelFrame frame = new PersonelFrame();

        MsSqlConnection msql = new MsSqlConnection();

        if (evt.getClickCount() == 1) {

            String sql = "select * from Personel order by adi";
            tablo.setModel(msql.eListele(sql));
        }
        if (evt.getClickCount() == 2) {

            String sql = "select * from Personel order by adi desc";

            tablo.setModel(msql.eListele(sql));

        }


    }//GEN-LAST:event_İSimSıralaButonMouseClicked

    private void SoyİsimSıralaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoyİsimSıralaMouseClicked
        PersonelFrame frame = new PersonelFrame();

        MsSqlConnection msql = new MsSqlConnection();

        if (evt.getClickCount() == 1) {

            String sql = "select * from Personel order by soyadi";

            tablo.setModel(msql.eListele(sql));
        }
        if (evt.getClickCount() == 2) {

            String sql = "select * from Personel order by soyadi desc";

            tablo.setModel(msql.eListele(sql));

        }


    }//GEN-LAST:event_SoyİsimSıralaMouseClicked

    private void DTSıralamaButonuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DTSıralamaButonuMouseClicked
        PersonelFrame frame = new PersonelFrame();

        MsSqlConnection msql = new MsSqlConnection();

        if (evt.getClickCount() == 1) {

            String sql = "select * from Personel order by dogTah";

            tablo.setModel(msql.eListele(sql));
        }
        if (evt.getClickCount() == 2) {

            String sql = "select * from Personel order by dogTah desc";

            tablo.setModel(msql.eListele(sql));

        }


    }//GEN-LAST:event_DTSıralamaButonuMouseClicked

    private void MaşşSıralamaButonuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaşşSıralamaButonuMouseClicked
        PersonelFrame frame = new PersonelFrame();

        MsSqlConnection msql = new MsSqlConnection();

        if (evt.getClickCount() == 1) {

            String sql = "select * from Personel order by maaş";

            tablo.setModel(msql.eListele(sql));
        }
        if (evt.getClickCount() == 2) {

            String sql = "select * from Personel order by maaş desc";

            tablo.setModel(msql.eListele(sql));

        }

    }//GEN-LAST:event_MaşşSıralamaButonuMouseClicked

    private void yŞehirSıralamaButonuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yŞehirSıralamaButonuMouseClicked
        PersonelFrame frame = new PersonelFrame();

        MsSqlConnection msql = new MsSqlConnection();

        if (evt.getClickCount() == 1) {

            String sql = "select * from Personel order by ySehir";

            tablo.setModel(msql.eListele(sql));
        }
        if (evt.getClickCount() == 2) {

            String sql = "select * from Personel order by ySehir desc";

            tablo.setModel(msql.eListele(sql));

        }


    }//GEN-LAST:event_yŞehirSıralamaButonuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new PersonelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AramaButon;
    private javax.swing.JTextField Aranan;
    private javax.swing.JButton DTSıralamaButonu;
    private javax.swing.JTextField ID;
    private javax.swing.JButton IDsıralamaButon;
    private javax.swing.JButton MaşşSıralamaButonu;
    private javax.swing.JTextField Soyad;
    private javax.swing.JButton SoyİsimSırala;
    private javax.swing.JButton SıralamaButon;
    private javax.swing.JComboBox<String> acombo;
    private javax.swing.JTextField ad;
    private javax.swing.JComboBox<String> ay;
    private javax.swing.JButton ekle;
    private javax.swing.JComboBox<String> gün;
    private javax.swing.JButton güncellemebutonu;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton listele;
    private javax.swing.JTextField maaş;
    private javax.swing.JComboBox<String> scombo;
    private javax.swing.JButton sil;
    private javax.swing.JTable tablo;
    private javax.swing.JTextField ySehir;
    private javax.swing.JTextField yıl;
    private javax.swing.JButton yŞehirSıralamaButonu;
    private javax.swing.JButton İSimSıralaButon;
    // End of variables declaration//GEN-END:variables
}
